name: calendar_flutter
description: Calendar app rewritten in Flutter supporting Web, iOS, and Android.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # TODO: 将 SVG 与其它资源拷贝至 flutter_app/assets 后取消注释
    # - assets/icons/
    # - assets/images/


